# -*- coding: utf-8 -*-
"""Deliverable9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nLPSPNcI_6W6zD1AkYj-L6Yad-Sw0MD-
"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
import pandas as pd
import numpy as np

df = pd.read_csv('/content/california_housing.csv')

cols = df.columns.to_list()
cols.remove('median_house_value')

features = df[cols]
response = df['median_house_value']

from sklearn.model_selection import train_test_split
features_train, features_test, response_train, response_test = train_test_split(features, response, test_size = 0.3, random_state = 0)

classifier = DecisionTreeClassifier(random_state = 0)
classifier.fit(features_train, response_train)

predictions = classifier.predict(features_test)
table = pd.DataFrame({'acutal':response_test, 'predictions': predictions})
table

from sklearn.metrics import accuracy_score
accuracy_score(response_test, predictions)

from sklearn.metrics import confusion_matrix
confusion_matrix(response_test, predictions)

from matplotlib import pyplot as plt
plt.figure(figsize=(15,5))
plt.bar(x = cols, height = classifier.feature_importances_)
plt.title("Feature Importance")
plt.xlabel("Features")
plt.ylabel("Importance Score")
plt.show()

"All categories are relatively important, but median income is the most important predictor for the model."